### ISSUE TITLE
NoClassDefFoundError: TypeSerializerCollection

### ISSUE THREAD

**Issue by skerit** [N3FS/gChat#10]
I'm trying to use version 2.1.0 (2.1.1 doesn't seem to have a prebuilt jar), but I get this error:

```
java.lang.NoClassDefFoundError: me/lucko/gchat/lib/configurate/objectmapping/serialize/TypeSerializerCollection
        at me.lucko.gchat.GChatPlugin.loadConfig(GChatPlugin.java:206) ~[?:?]
        at me.lucko.gchat.GChatPlugin.onEnable(GChatPlugin.java:104) ~[?:?]
        at net.kyori.event.asm.generated.592445aa1b.GChatPlugin-onEnable-ProxyInitializeEvent-8.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[1.1.0.jar:1.1.0]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[1.1.0.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[1.1.0.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[1.1.0.jar:1.1.0]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.gchat.lib.configurate.objectmapping.serialize.TypeSerializerCollection
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[1.1.0.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[1.1.0.jar:1.1.0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 11 more
```
I'm using the Velocity v1.1.0 stable release, do I have to be using 1.1.2?

**Comment by mdcfe** [comment]
Could you test on [this dev build](https://github.com/N3FS/gChat/suites/1523480280/artifacts/26893344)?

**Comment by skerit** [comment]
Tried it, but now I get this error:

```
[00:22:34 ERROR]: #1: 

java.lang.NoClassDefFoundError: net/kyori/adventure/serializer/configurate3/ConfigurateComponentSerializer
        at me.lucko.gchat.GChatPlugin.loadConfig(GChatPlugin.java:207) ~[?:?]
        at me.lucko.gchat.GChatPlugin.onEnable(GChatPlugin.java:104) ~[?:?]
        at net.kyori.event.asm.generated.0b0ba2e744.GChatPlugin-onEnable-ProxyInitializeEvent-9.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[1.1.0.jar:1.1.0]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[1.1.0.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[1.1.0.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[1.1.0.jar:1.1.0]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.serializer.configurate3.ConfigurateComponentSerializer
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[1.1.0.jar:1.1.0]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[1.1.0.jar:1.1.0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 11 more
```

Also tried it with the Velocity 1.1.x snapshot version, but keep getting the same issue.

**Comment by skerit** [comment]
Well, managed to fix it: just had to change the scope of the dependency to `compile` instead of `provided` in the pom.xml file

**Comment by mdcfe** [comment]
This should be fixed by 81854130c615fa75609e0c731c574e2886eebd82 - could you try the latest builds of [gChat](https://github.com/N3FS/gChat/suites/1744168256/artifacts/33120159) and [gCV-Bridge](https://github.com/N3FS/gChat/files/5754734/gCV-Bridge-0.3-SNAPSHOT-dev-10.jar.zip)?

**Comment by andrewzah** [comment]
@mdcfe I get this error now. This is with a brand new config generated by gcv-bridge (after I added a bot token):

```
[15:59:28 INFO] [gchat-velocity]: Enabling gChat v2.1.2-SNAPSHOT-dev-
[15:59:28 INFO] [gcv-bridge]: Enabling gCV-Bridge v0.3-SNAPSHOT-dev-10
[15:59:28 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[15:59:28 ERROR]: #1:

java.lang.RuntimeException: Failed to load config
        at uk.co.n3fs.mc.gcvbridge.GCVBridge.onProxyInit(GCVBridge.java:65) ~[?:?]
        at net.kyori.event.asm.generated.a017612ad8.GCVBridge-onProxyInit-ProxyInitializeEvent-6.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity-1.1.2.jar:1.1.2]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity-1.1.2.jar:1.1.2]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[velocity-1.1.2.jar:1.1.2]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[velocity-1.1.2.jar:1.1.2]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at uk.co.n3fs.mc.gcvbridge.GCVBConfig.<init>(GCVBConfig.java:58) ~[?:?]
        at uk.co.n3fs.mc.gcvbridge.GCVBridge.loadConfig(GCVBridge.java:118) ~[?:?]
        at uk.co.n3fs.mc.gcvbridge.GCVBridge.onProxyInit(GCVBridge.java:63) ~[?:?]
        ... 9 more
[15:59:28 INFO]: Done (1.02s)!
```

**Comment by mdcfe** [comment]
I've pushed https://github.com/N3FS/gCV-Bridge/commit/65c245292a3d30380e7c0da609e141d75dd6c97b which should fix this (although now I'm lost as to how those builds worked for me). Try this build of gCV-Bridge along with the previous build of gChat: [gCV-Bridge-0.3-SNAPSHOT-dev-11.jar.zip](https://github.com/N3FS/gChat/files/5754875/gCV-Bridge-0.3-SNAPSHOT-dev-11.jar.zip)

**Comment by andrewzah** [comment]
:+1: those work for me.

**Comment by andrewzah** [comment]
Note that I can't seem to build gcv-bridge locally with `2.1.2-SNAPSHOT` as the version for gchat. I had to change it to `2.1.0` to get it to compile.

**Comment by mdcfe** [comment]
`2.1.2-SNAPSHOT` is the current dev version of gChat; you'd need to manually edit the pom to point at a jar of that version for now. I'll publish non-snapshot versions of everything when we can confirm it's working for everyone.

**Comment by skerit** [comment]
Nothing is working for me. The link posted to the gChat dev build (the github `suites` link) doesn't work anymore.
And the `gChat-Velocity-2.1.2-SNAPSHOT-dev-5.jar` file I do have will only work if I recompile Velocity with `api("net.kyori:adventure-serializer-configurate3")` added to the `api/build.gradle` file
