### ISSUE TITLE
NoSuchMethodError: GChatMessageFormedEvent.getMessage

### ISSUE THREAD

**Issue by skerit** [N3FS/gChat#11]
After working around issue #10 I now get this error:

```
[14:30:54 INFO] [gchat-velocity]: -Skerit-It is I
[14:30:54 ERROR]: Some errors occurred whilst posting event GChatMessageFormedEvent(sender=[connected player] Skerit (/213.219.145.208:33500), format=ChatFormat(id=everyone, priority=100, checkPermission=false, formatText={luckperms_prefix}-{display_name}-{luckperms_suffix}{message}, hoverText=null, clickType=null, clickValue=null), rawMessage=It is I, message=TextComponentImpl{content="-Skerit-It is I", children=[], style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}}).
[14:30:54 ERROR]: #1: 

java.lang.NoSuchMethodError: 'net.kyori.text.Component me.lucko.gchat.api.events.GChatMessageFormedEvent.getMessage()'
        at uk.co.n3fs.mc.gcvbridge.velocity.GChatListener.onGChatMessage(GChatListener.java:20) ~[?:?]
        at net.kyori.event.asm.generated.fbabdb3577.GChatListener-onGChatMessage-GChatMessageFormedEvent-41.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[1.1.x-SNAPSHOT.jar:1.1.2-SNAPSHOT (git-3d0cb505-b319)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[1.1.x-SNAPSHOT.jar:1.1.2-SNAPSHOT (git-3d0cb505-b319)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[1.1.x-SNAPSHOT.jar:1.1.2-SNAPSHOT (git-3d0cb505-b319)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fireAndForget$2(VelocityEventManager.java:133) ~[1.1.x-SNAPSHOT.jar:1.1.2-SNAPSHOT (git-3d0cb505-b319)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by skerit** [comment]
Oops, only now realized this is an issue in the gCV-Bridge

**Comment by skerit** [comment]
And now I realize this is in fact an issue in gChat. Somehow the getters are not being generated in the GChatMessageFormedEvent file.

I think it's because of the Lombok stuff? I tried adding `maven-compiler-plugin` and accompanying `annotationProcessorPaths` settings to the pom.xml file, but then I get problems with other decorators (like com.google.inject not being found)

So I'm confused: is the pom.xml just not up to date, or how do you compile this?

**Comment by andrewzah** [comment]
Having the same issue.

**Comment by andrewzah** [comment]
@skerit I got it to work. Keep in mind I don't really know how maven works at all.

1. I made these changes to gCV-Bridge's pom.xml
```diff
--- a/pom.xml
+++ b/pom.xml
@@ -187,8 +187,8 @@
         <dependency>
             <groupId>uk.co.n3fs.mc</groupId>
             <artifactId>gchat-velocity</artifactId>
-            <version>2.0.2</version>
-            <scope>provided</scope>
+            <version>2.1.0</version>
+            <scope>compile</scope>
```

2. I had an older version of gChat-Velocity so I built that with some changes to its pom.xml:
```diff
--- a/pom.xml
+++ b/pom.xml
@@ -140,7 +140,7 @@
             <groupId>net.kyori</groupId>
             <artifactId>adventure-serializer-configurate3</artifactId>
             <version>4.1.1</version>
-            <scope>provided</scope>
+            <scope>runtime</scope>
         </dependency>
```
my final plugins are
```sh
gChat-Velocity-2.1.2-SNAPSHOT-dev-3.jar
gCV-Bridge-0.3-SNAPSHOT-dev-8.jar
# for velocity-1.1.2
```

Hope this helps.

---

I did set up Lombok with intellij idea pro.

FWIW I do get this reflection message, and I'm not sure if it's related to my changes or not:
```
ARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/guest/mcserver/velocity-1.1.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
```

**Comment by mdcfe** [comment]
@skerit 
> Somehow the getters are not being generated in the GChatMessageFormedEvent file.

Looks like the gCV-Bridge build you used depends on gChat-Velocity from back when it used text 3 instead of adventure.

> I tried adding `maven-compiler-plugin` and accompanying `annotationProcessorPaths` settings to the pom.xml file, but then I get problems with other decorators (like com.google.inject not being found)

Adding `adventure-serializer-configurate3` as a `compile` dependency causes Guice to become a `runtime` dependency rather than `provided` (which is what Velocity specifies and normally pulls in). 

@andrewzah
> FWIW I do get this reflection message, and I'm not sure if it's related to my changes or not: [...]

This occurs when using Guice 4.x or below on Java 9+ due to module changes. You can safely ignore this message.

---

Both this issue and #10 should be resolved by using the latest dev builds, which you can find here: https://github.com/N3FS/gChat/issues/10#issuecomment-752666219

Once we can confirm that this fixes the issue, I'll release proper updates for both gChat and gCV-Bridge.

**Comment by skerit** [comment]
Oh good I'll try that. (Until now I recompiled Paper with adventure-serializer-configurate3 as a dependency)
