### ISSUE TITLE
Issue with gchat

### ISSUE THREAD

**Issue by RadNotRed** [N3FS/gChat#14]
Couldn't pass ProxyInitializeEvent to gchat-velocity

`[00:06:36 ERROR]: Couldn't pass ProxyInitializeEvent to gchat-velocity
java.lang.NoClassDefFoundError: net/kyori/text/Component
        at me.lucko.gchat.config.TypeTokens.<clinit>(TypeTokens.java:11) ~[?:?]
        at me.lucko.gchat.GChatPlugin.loadConfig(GChatPlugin.java:204) ~[?:?]
        at me.lucko.gchat.GChatPlugin.onEnable(GChatPlugin.java:100) ~[?:?]
        at me.lucko.gchat.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[velocity.jar:3.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.text.Component
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity.jar:3.0.0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 10 more`

**Comment by jackmawer** [comment]
Thanks for your issue. gChat-Velocity doesn’t yet support Velocity 3.0.0 - as a workaround, you can temporarily downgrade to [Velocity 1.1.9](https://versions.velocitypowered.com/download/1.1.9.jar).

**Comment by skerit** [comment]
@jackmawer The 3.0.0 changes were committed last month, but I'm still getting the same error.

Edit: I was using the non `-all` package, so I was missing some dependencies.

**Comment by alvarlagerlof** [comment]
Is there a 3.0 build that works?

**Comment by purejosh** [comment]
dead plugin. big sad. not downgrading to a legacy server to run a plugin.

**Comment by BBaoVanC** [comment]
Hm that's weird, it's been working fine for me on latest velocity
